<?php

namespace BestChange;

/**
 * Коды взяты отсюда: https://www.bestchange.ru/wiki/rates.html
 * нет API для получения кода валют
 */
class ECurrencyCodes
{
    public function __construct()
    {
    }

    public function get()
    {
        return [
            'WMZ' => ['name' => 'WMZ', 'id' => 1],
            'WMR' => ['name' => 'WMR', 'id' => 2],
            'WME' => ['name' => 'WME', 'id' => 3],
            'WMU' => ['name' => 'WMU', 'id' => 20],
            'WMB' => ['name' => 'WMB', 'id' => 18],
            'WMK' => ['name' => 'WMK', 'id' => 47],
            'WMG' => ['name' => 'WMG', 'id' => 43],
            'WMX' => ['name' => 'WMX', 'id' => 96],
            'PMRUSD' => ['name' => 'Paymer USD', 'id' => 87],
            'PMRRUB' => ['name' => 'Paymer RUB', 'id' => 144],
            'PMREUR' => ['name' => 'Paymer EUR', 'id' => 171],
            'PMRUAH' => ['name' => 'Paymer UAH', 'id' => 19],
            'YAMRUB' => ['name' => 'Яндекс.Деньги', 'id' => 6],
            'QWUSD' => ['name' => 'QIWI USD', 'id' => 110],
            'QWRUB' => ['name' => 'QIWI RUB', 'id' => 63],
            'QWEUR' => ['name' => 'QIWI EUR', 'id' => 126],
            'QWKZT' => ['name' => 'QIWI KZT', 'id' => 127],
            'PMUSD' => ['name' => 'Perfect Money USD', 'id' => 40],
            'PMEUR' => ['name' => 'Perfect Money EUR', 'id' => 41],
            'PMBTC' => ['name' => 'Perfect Money BTC', 'id' => 128],
            'PMVUSD' => ['name' => 'PM e-Voucher USD', 'id' => 156],
            'PPUSD' => ['name' => 'PayPal USD', 'id' => 45],
            'PPRUB' => ['name' => 'PayPal RUB', 'id' => 98],
            'PPEUR' => ['name' => 'PayPal EUR', 'id' => 80],
            'PPGBP' => ['name' => 'PayPal GBP', 'id' => 164],
            'BTC' => ['name' => 'Bitcoin (BTC)', 'id' => 93],
            'BCH' => ['name' => 'Bitcoin Cash (BCH)', 'id' => 172],
            'ETH' => ['name' => 'Ethereum (ETH)', 'id' => 139],
            'ETC' => ['name' => 'Ether Classic (ETC)', 'id' => 160],
            'LTC' => ['name' => 'Litecoin (LTC)', 'id' => 99],
            'XRP' => ['name' => 'Ripple (XRP)', 'id' => 161],
            'XMR' => ['name' => 'Monero (XMR)', 'id' => 149],
            'DOGE' => ['name' => 'Dogecoin (DOGE)', 'id' => 115],
            'NMC' => ['name' => 'Namecoin (NMC)', 'id' => 137],
            'PPC' => ['name' => 'Peercoin (PPC)', 'id' => 138],
            'DASH' => ['name' => 'Dash (DASH)', 'id' => 140],
            'ZEC' => ['name' => 'Zcash (ZEC)', 'id' => 162],
            'USDT' => ['name' => 'Tether (USDT)', 'id' => 163],
            'XEM' => ['name' => 'NEM (XEM)', 'id' => 173],
            'REP' => ['name' => 'Augur (REP)', 'id' => 174],
            'WEXUSD' => ['name' => 'WEX USD', 'id' => 104],
            'WEXRUB' => ['name' => 'WEX RUB', 'id' => 112],
            'WEXEUR' => ['name' => 'WEX EUR', 'id' => 119],
            'WEXBTC' => ['name' => 'WEX BTC', 'id' => 170],
            'EXMUSD' => ['name' => 'Exmo USD', 'id' => 129],
            'EXMRUB' => ['name' => 'Exmo RUB', 'id' => 130],
            'EXMEUR' => ['name' => 'Exmo EUR', 'id' => 131],
            'EXMUAH' => ['name' => 'Exmo UAH', 'id' => 169],
            'CRPCUSD' => ['name' => 'Cryptocheck', 'id' => 146],
            'ECNEXUSD' => ['name' => 'eCoin', 'id' => 7],
            'LVCNUSD' => ['name' => 'LiveCoin', 'id' => 82],
            'TRDUSD' => ['name' => 'Криптобиржи USD', 'id' => 148],
            'TRDEUR' => ['name' => 'Криптобиржи EUR', 'id' => 153],
            'ADVCUSD' => ['name' => 'Advanced Cash USD', 'id' => 88],
            'ADVCRUB' => ['name' => 'Advanced Cash RUB', 'id' => 121],
            'ADVCEUR' => ['name' => 'Advanced Cash EUR', 'id' => 120],
            'ADVCUAH' => ['name' => 'Advanced Cash UAH', 'id' => 142],
            'PRUSD' => ['name' => 'Payeer USD', 'id' => 108],
            'PRRUB' => ['name' => 'Payeer RUB', 'id' => 117],
            'PREUR' => ['name' => 'Payeer EUR', 'id' => 122],
            'SKLUSD' => ['name' => 'Skrill USD', 'id' => 44],
            'SKLEUR' => ['name' => 'Skrill EUR', 'id' => 123],
            'PAUSD' => ['name' => 'Payza USD', 'id' => 66],
            'PAEUR' => ['name' => 'Payza EUR', 'id' => 124],
            'OKUSD' => ['name' => 'OKPay USD', 'id' => 83],
            'OKRUB' => ['name' => 'OKPay RUB', 'id' => 84],
            'OKEUR' => ['name' => 'OKPay EUR', 'id' => 85],
            'WOUSD' => ['name' => 'W1 USD', 'id' => 61],
            'WOUAH' => ['name' => 'W1 UAH', 'id' => 46],
            'IDAMD' => ['name' => 'Idram', 'id' => 11],
            'PAXUMUSD' => ['name' => 'Paxum USD', 'id' => 74],
            'PAXUMEUR' => ['name' => 'Paxum EUR', 'id' => 133],
            'CPTSUSD' => ['name' => 'Capitalist', 'id' => 145],
            'EPSUSD' => ['name' => 'Epese', 'id' => 147],
            'MPLUSD' => ['name' => 'MoneyPolo USD', 'id' => 134],
            'MPLEUR' => ['name' => 'MoneyPolo EUR', 'id' => 135],
            'NTLRUSD' => ['name' => 'Neteller USD', 'id' => 72],
            'NTLREUR' => ['name' => 'Neteller EUR', 'id' => 136],
            'PSRUSD' => ['name' => 'PaySera', 'id' => 152],
            'PSCEUR' => ['name' => 'PaySafeCard', 'id' => 73],
            'STPUSD' => ['name' => 'SolidTrust Pay', 'id' => 76],
            'NIXUSD' => ['name' => 'NixMoney USD', 'id' => 109],
            'NIXEUR' => ['name' => 'NixMoney EUR', 'id' => 125],
            'EPAYUSD' => ['name' => 'Epay USD', 'id' => 154],
            'EPAYEUR' => ['name' => 'Epay EUR', 'id' => 97],
            'ALPCNY' => ['name' => 'Alipay', 'id' => 165],
            'LQUSD' => ['name' => 'LiqPay', 'id' => 50],
            'EKZT' => ['name' => 'E-kzt', 'id' => 155],
            'ZPRUB' => ['name' => 'Z-Payment', 'id' => 48],
            'MWRUB' => ['name' => 'Баланс телефона', 'id' => 49],
            'SBERRUB' => ['name' => 'Сбербанк', 'id' => 114],
            'ACRUB' => ['name' => 'Альфа-Банк', 'id' => 52],
            'ACCUSD' => ['name' => 'Альфа cash-in USD', 'id' => 143],
            'ACCRUB' => ['name' => 'Альфа cash-in RUB', 'id' => 62],
            'TCSBRUB' => ['name' => 'Тинькофф', 'id' => 105],
            'TBRUB' => ['name' => 'ВТБ24', 'id' => 51],
            'RUSSTRUB' => ['name' => 'Русский Стандарт', 'id' => 64],
            'AVBRUB' => ['name' => 'Авангард', 'id' => 79],
            'PSBRUB' => ['name' => 'Промсвязьбанк', 'id' => 53],
            'GPBRUB' => ['name' => 'Газпромбанк', 'id' => 95],
            'KUKRUB' => ['name' => 'Кукуруза', 'id' => 57],
            'RFBRUB' => ['name' => 'Райффайзен', 'id' => 157],
            'RNKBRUB' => ['name' => 'РНКБ', 'id' => 132],
            'P24USD' => ['name' => 'Приват 24 USD', 'id' => 55],
            'P24UAH' => ['name' => 'Приват 24 UAH', 'id' => 56],
            'RFBUAH' => ['name' => 'Райффайзен UAH', 'id' => 158],
            'OSDBUAH' => ['name' => 'Ощадбанк', 'id' => 68],
            'PMBBUAH' => ['name' => 'ПУМБ', 'id' => 118],
            'BLRBBYN' => ['name' => 'Беларусбанк', 'id' => 4],
            'KKBKZT' => ['name' => 'Казкоммерцбанк', 'id' => 103],
            'HLKBKZT' => ['name' => 'HalykBank', 'id' => 90],
            'SBERKZT' => ['name' => 'Сбербанк KZT', 'id' => 114],
            'FRTBKZT' => ['name' => 'ForteBank', 'id' => 75],
            'ATNBKZT' => ['name' => 'Банк Астаны', 'id' => 168],
            'UPCNY' => ['name' => 'UnionPay', 'id' => 100],
            'CARDUSD' => ['name' => 'Visa/MasterCard USD', 'id' => 58],
            'CARDRUB' => ['name' => 'Visa/MasterCard RUB', 'id' => 59],
            'CARDEUR' => ['name' => 'Visa/MasterCard EUR', 'id' => 65],
            'CARDUAH' => ['name' => 'Visa/MasterCard UAH', 'id' => 60],
            'CARDBYN' => ['name' => 'Visa/MasterCard BYN', 'id' => 54],
            'CARDKZT' => ['name' => 'Visa/MasterCard KZT', 'id' => 111],
            'WIREUSD' => ['name' => 'Любой банк USD', 'id' => 69],
            'WIRERUB' => ['name' => 'Любой банк RUB', 'id' => 71],
            'WIREEUR' => ['name' => 'Любой банк EUR', 'id' => 70],
            'WIREUAH' => ['name' => 'Любой банк UAH', 'id' => 102],
            'WIREKZT' => ['name' => 'Любой банк KZT', 'id' => 113],
            'WIREGBP' => ['name' => 'Любой банк GBP', 'id' => 81],
            'WIRECNY' => ['name' => 'Любой банк CNY', 'id' => 166],
            'WIRETHB' => ['name' => 'Любой банк THB', 'id' => 167],
            'STLMRUB' => ['name' => 'Счет ИП или ООО', 'id' => 159],
            'WUUSD' => ['name' => 'Western Union USD', 'id' => 67],
            'WUEUR' => ['name' => 'Western Union EUR', 'id' => 15],
            'MGUSD' => ['name' => 'MoneyGram USD', 'id' => 78],
            'MGEUR' => ['name' => 'MoneyGram EUR', 'id' => 77],
            'CNTUSD' => ['name' => 'Contact USD', 'id' => 101],
            'CNTRUB' => ['name' => 'Contact RUB', 'id' => 106],
            'GCMTUSD' => ['name' => 'Золотая Корона USD', 'id' => 116],
            'GCMTRUB' => ['name' => 'Золотая Корона RUB', 'id' => 107],
            'USTMUSD' => ['name' => 'Юнистрим', 'id' => 86],
            'RMTFUSD' => ['name' => 'Ria USD', 'id' => 150],
            'RMTFEUR' => ['name' => 'Ria EUR', 'id' => 151],
            'CASHUSD' => ['name' => 'Наличные USD', 'id' => 89],
            'CASHRUB' => ['name' => 'Наличные RUB', 'id' => 91],
            'CASHEUR' => ['name' => 'Наличные EUR', 'id' => 141],
            'CASHUAH' => ['name' => 'Наличные UAH', 'id' => 92],
            'CASHKZT' => ['name' => 'Наличные KZT', 'id' => 94],
        ];
    }
}
